# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-01 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_bugreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(default='default.jpg', upload_to='About_Profile')),
                ('description', models.TextField()),
                ('contact', models.CharField(max_length=256)),
            ],
        ),
    ]
