# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-01 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('profile', models.ImageField(default='default.jpg', upload_to='About_Profile')),
                ('description', models.TextField()),
                ('contact', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
